scraper_itit_settings:
  eton:
      site_name: eaton.com
      base_url: https://www.eaton.com/us/en-us/company/news-insights/news-releases.html
      header:
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0
      search_result_container_name: results-list-submodule results-list-submodule--type-news-and-insights
  reuters:
      site_name: reuters.com
      background_url: https://www.reuters.com
      search_url: /tags/mergers-acquisitions/
      header:
          User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0
      search_result_container_name: search-results__item__2oqiX
num_articles: 10